ibm-granite/granite-io

README.md, src/granite_io/backend/openai.py, src/granite_io/io/granite_3_2.py
This PR addresses a few key bugs that blocked the desired quick start experience and adds the `Quick Start` section to the README.
=> Quick start / setup bugs

README.md, examples/inference.py, examples/inference_with_thinking.py, tox.ini
Adds the following examples:
- Granite 3.2 chat request
- Granite 3.2 chat request with thinking
=> Add example python scripts

README.md, examples/model_chat.py, examples/model_chat_with_thinking.py, notebooks/io.ipynb, pyproject.toml
Some improvements to help users when landing on the framework:
- Improvements to README
- Improvements to example scripts
- Bug fixes in the IO notebook
=> Updates to improve usability

README.md, examples/model_chat.py, examples/model_chat_with_thinking.py, notebooks/io.ipynb
Some fixes required following the release of the Granite 3.2 model.
=> fix: Updates following Granite 3.2 release

.github/workflows/test.yml, notebooks/io.ipynb, tox.ini
* tox -e notebooks
* No output tests now, but can fail when we change code
* Updated notebook for future PR #30 (asyncio)
=> Add simple tests to make sure notebooks run

README.md, tox.ini
Parser uses the [NLTK Data](https://www.nltk.org/data.html) [Punkt Sentence Tokenizer](https://www.nltk.org/api/nltk.tokenize.punkt.html) for extracting contents when parsing output from a model. This PR adds instructions on how to install the tokenizer required by `granite-io`.
It also updates tox environment to install `punkt` resource only as not all data is required.
=> doc: Add details on nltk data

.github/workflows/test_examples.yml, tox.ini
=> ci: Re-enable disabled example tests

src/granite_io/types.py
Cleaned up the GenerateInputs type with the first set of fields from LiteLLM (and OpenAI).
Just missed getting this in before it was merged.
=> Clean up generate input type fields

src/granite_io/io/granite_3_2/output_processors/granite_3_2_output_processor.py, src/granite_io/types.py, tests/io/granite_3_2/output_processors/test_granite_3_2_output_processor.py
This PR adds basic tool parsing for Granite 3.2 output, as well as a test case.
Closes #49
=> Basic tool parsing for Granite 3.2

src/granite_io/io/granite_3_2/input_processors/granite_3_2_input_processor.py, tests/io/granite_3_2/test_granite_3_2.py
=> field validators for length and originality

src/granite_io/backend/base.py
* Objects as params in python can be modified.  We can make a copy to no user is caught off guard.
* New object is returned with modifications (was orig object with modifications).
Closes: #94
=> don't modify backend inputs arg, only return modified inputs

docs/design.md
* Mostly typo-ish stuff
* Tried to fix some wording that threw me off, but mine isn't always better so tried to limit those
=> docs: edit the design.md for nits like typos

src/granite_io/io/granite_3_2/output_processors/granite_3_2_output_parser.py, tests/io/granite_3_2/output_processors/test_granite_3_2_output_parser.py, tests/io/granite_3_2/output_processors/testdata/test_output_with_multiple_citations_per_document.txt
Fixes: #125
**Note:** ~This is built on top of  #121. **DO NOT MERGE** until #121 merges first.~ Ready for review now as #121 is merged.
=> Support seperate citations referencing the same document

src/granite_io/io/granite_3_2/output_processors/granite_3_2_output_parser.py
Fix for comment https://github.com/ibm-granite/granite-io/pull/121#discussion_r2033722909
=> Follow up fix to PR #121

src/granite_io/io/granite_3_2/input_processors/granite_3_2_input_processor.py, tests/io/granite_3_2/cassettes/test_granite_3_2/test_multiple_return[backend_openai-custom_system_prompt].yaml, tests/io/granite_3_2/cassettes/test_granite_3_2/test_run_processor[backend_litellm-custom_system_prompt].yaml, tests/io/granite_3_2/cassettes/test_granite_3_2/test_run_processor[backend_openai-custom_system_prompt].yaml, tests/io/granite_3_2/test_granite_3_2.py
This PR fixes a bug in the handling of custom system prompts in the Granite 3.2 input processor. The PR also adds a test case for the original issue.
Before this change, the Granite 3.2 input processor will ignore any custom system prompt. Custom system prompts have zero effect before this change.
=> Fix for bug with custom system prompts

README.md, pyproject.toml, tox.ini
=> Remove deprecated punkt (keep punkt_tab) update nltk

src/granite_io/io/granite_3_3/input_processors/granite_3_3_input_processor.py, tests/io/granite_3_3/input_processors/testdata/test_reasoning_prompt.txt, tests/io/granite_3_3/test_granite_3_3.py
This PR updates the IO processor and test cases for Granite 3.3 to reflect the changes from https://huggingface.co/ibm-granite/granite-3.3-8b-instruct/commit/838cee30ab44b5d8011a2ed5c6851bacc2af9c15
=> Update Granite 3.3 IO processor to reflect latest template

notebooks/intrinsics.ipynb, notebooks/rag.ipynb, src/granite_io/types.py
This PR includes a shorter version of `rag.ipynb` with a slightly different example conversation. This shorter notebook allows for a 15-minute demo instead of 30 minutes.
This change set also adds a convenience method for changing the messages list of a chat completion request, since we seem to be doing that operation frequently.
=> Simpler demo notebook for Granite intrinsics

src/granite_io/types.py
Fix for issue #181, see issue for more details and the simple fix that's in this PR.
=> Fix for issue 181 - watsonx litellm throwing an error

notebooks/mbrd.ipynb
New notebook `notebooks/mbrd.ipynb` to demo MBRD with a math problem
=> MBRD notebook added

pyproject.toml, src/granite_io/io/granite_3_2/input_processors/granite_3_2_input_processor.py, src/granite_io/io/granite_3_3/input_processors/granite_3_3_input_processor.py, src/granite_io/types.py, tests/conftest.py, tests/io/granite_3_2/cassettes/test_granite_3_2/test_multiple_return[backend_openai-functions].yaml, tests/io/granite_3_2/cassettes/test_granite_3_2/test_run_processor[backend_litellm-functions].yaml, tests/io/granite_3_2/cassettes/test_granite_3_2/test_run_processor[backend_openai-functions].yaml, tests/io/granite_3_2/output_processors/test_granite_3_2_output_processor.py, tests/io/granite_3_2/test_granite_3_2.py, tests/io/granite_3_3/cassettes/test_granite_3_3/test_multiple_return[backend_3_3_openai-functions].yaml, tests/io/granite_3_3/cassettes/test_granite_3_3/test_run_processor[backend_3_3_litellm-functions].yaml, tests/io/granite_3_3/cassettes/test_granite_3_3/test_run_processor[backend_3_3_openai-functions].yaml, tests/io/granite_3_3/output_processors/test_granite_3_3_output_processor.py, tests/io/granite_3_3/test_granite_3_3.py, tests/io/test_rerank.py, tests/test_types.py
This PR addresses issues with generating tool call prompts with the input processors for Granite 3.2 and 3.3. I also fixed a number of broken tests that were exposed by these changes.
Closes #186
=> Fix tool calling on Granite 3.2 and 3.3
