- .github/workflows/test.yml
- tests/io/test_granite_3_2.py
Get the filter out of the CI workflow.
Allow CI to xfail since we don't have OpenAI running. Allow devs to run w/ or w/o OpenAI (e.g. ollama).
Probably more skipability coming, but this handles it for now.
> tests: use xfail (xpass) for OpenAI tests

- .github/workflows/pypi.yml
- pyproject.toml
This PR adds GitHub actions to perform the following:
- Build Python package and publish to [TestPyPi](https://packaging.python.org/en/latest/guides/using-testpypi/) when PR merged or GH release is published
- Build Python package and publish to [PyPi](https://pypi.org/) when GH release is published
Publishing to [TestPyPI](https://packaging.python.org/en/latest/guides/using-testpypi/) provides intermediate packages between releases and helps identify any issues with the package early instead of at release time.
The package published name is `granite-io`.
> CI: Add PyPi publishing

- tests/io/test_granite_3_2.py
Need to set backend=backend because first param
is config.
> tests: fix test failing on backend=None

- README.md
- examples/inference.py
- examples/inference_with_thinking.py
- src/granite_io/io/base.py
- src/granite_io/io/granite_3_2.py
- src/granite_io/types.py
- tests/test_types.py
This PR introduces output parsing for granite 3.2 Chain of Thought. It also makes a few subtle architectural updates:
* It allows arbitrary attributes to be accessed on the `ChatCompletionInputs` and `ChatCompletionResult` objects and safely return `None`. This allows both IO processor implementations and user scripts to treat all derived types the same and only do `None` checks without needing a lot of `isinstance` checks or `AttributeError` handling.
* It changes the abstract interface of `ModelDirectInputOutputProcessor` so that derived classes have full control over creating the `ChatCompletionResult` object (or a derived superset type)
> Chain of Thought Parsing

- README.md
- pyproject.toml
- tox.ini
The restriction for version < 3.12 no longer applies due to vLLM is no longer started from library.
> Remove upper band restriction on Python version

- README.md
- examples/watsonx_litellm.py
- pyproject.toml
- src/granite_io/backend/__init__.py
- src/granite_io/backend/litellm.py
- tests/io/test_granite_3_2.py
- tox.ini
LiteLLM supports watsonx, ollama and others.  I could not get it to work with RITS so it is yet another limited proxy for backend providers (otherwise maybe it would replace our openai backend).
LiteLLM uses environment variables for much of the control over backends, so there is a new example using a .env file to show how to make the example work with either watsonx or ollama.
> Use watsonx with LiteLLM backend

- README.md
- examples/model_chat_with_thinking.py
- src/granite_io/io/granite_3_2.py
- src/granite_io/types.py
- tests/io/test_granite_3_2.py
Closes #20 
This PR addresses the outstanding issues from the original CoT parsing PR that we opted to defer to after-release. Specifically, it does the following:
* Moves the `reasoning_content` field into the `next_message`
* Adds the `raw` logical-field to `AssistantMessage`
* Adds robustness for different forms of the CoT tags
* Applies stripping to reasoning / result content for Granite 3.2, relying on `.raw` for round-trip serialization
> CoT robustness

- .github/workflows/test.yml
- .github/workflows/test_examples.yml
paths was restricting when the test runs. It should run anytime code changes that might break the examples.
> ci: test examples when code changes

- .github/workflows/test_examples.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/granite_io/io/granite_3_2/granite_output_parser.py
- tox.ini
- Test examples, notebboks and readme by default in tox run
- Disable litellm example for now until async issue resolved
- Refactor examples workflow to use the tox targets instead
- Updated ruff version in pre-commit to align with project version
- Remove print statements from parser
- Allow job steps to continue if "test notebooks" step fails
Fixed #62
> ci: Refactor examples, notebook and readme tests

- tests/io/granite_3_2/input_processors/test_granite_3_2_input_processor.py
- tests/io/granite_3_2/output_processors/test_granite_3_2_output_parser.py
- tests/io/granite_3_2/output_processors/test_granite_3_2_output_processor.py
- tests/test_utils.py
Failing test:
`tests/io/granite_3_2/input_processors/test_granite_3_2_input_processor.py::test_run_processor_reasoning`
This commit fixes the test and also adds a function for loading test text file used by multiple tests.
> Fix failing unit test

- .gitignore
- CONTRIBUTING.md
- notebooks/.gitignore
- pyproject.toml
Updates as follows:
- Realign `.gitignore` file with [Python standard](https://github.com/github/gitignore/blob/main/Python.gitignore)
- Updated contributing guide to add installing `dev` package dependencies (fixes #33)
- Remove `.gitignore` file in `notebooks` directory. Entry doesn't look like it needs to be added to main ignore file.
- Linting warning on `pylint_pydantic` package:
```shell
Command line or configuration file:1:0: E0013: Plugin 'pylint_pydantic' is impossible to load, is it installed ? ('No module named 'pylint_pydantic'') (bad-plugin-value)
```
> dev: Updates to development environment

- src/granite_io/types.py
To support timeout for openai and litellm, I introduced an httpx dependency that we don't want in io.  We can remove timeout field since we don't add any value with it (would only limit it's httpx features).
This should fall into "other params" that we don't want to have an opinion about.  If/when we do care, we'll need to handle httpx in/out for this dataclass in an import optional way.
Closes: #84
> bug: remove httpx dependency and timeout field

- examples/watsonx_litellm.py
We can use LiteLLM to access Replicate
The examples/watsonx_litellm.py explains how to use environment variables to make LiteLLM work with watsonx, Ollama, and now Replicate (with a thinking/non-thinking example).
This example filename is not great, but emphasizing watsonx is OK. Need to follow-up with better docs explaining what is supported and link to examples from there. Separate issue coming for that.
Closes: #90
> feat: add example for how to use Replicate

- src/granite_io/io/granite_3_2/input_processors/granite_3_2_input_processor.py
Fixes an issues where the prompt parts for `NO_TOOLS_AND_DOCS` and `TOOLS_AND_NO_DOCS` were mixed up. 
To fix I swapped the contents of the variables and updated the comments.
Fixes #111
> fix: swap no_tools_docs and tools_no_docs  parts

- examples/watsonx_litellm.py
- pyproject.toml
Closes: #91
The main issue is logging errors (after an error) with latest litellm and openai. Also setting pydantic minimum version to be compatible with litellm.
> fix: pin litellm, openai and pydantic to compatible versions

- src/granite_io/backend/openai.py
- src/granite_io/types.py
- tests/io/granite_3_2/test_granite_3_2.py
- tests/test_backends.py
* default_headers is a config setting that openai can use
* extra_headers works for openai and litellm
* either of these can be used to get rid of some code specific to an internal provider header and also useful for testing various providers
* Test is skipped, but can be used for manual testing against alternate server to prove effectiveness
* Env vars that are used in the test are the standard ones already recognized by the client.
Closes: #39
> feat: add extra_headers to GenerateInputs

- src/granite_io/types.py
Using the same style as pydantic.BaseModel allows the field doc strings to show on hovers for vscode or pycharm.
Closes: #93
> chore: formatting pydantic field doc strings for GenerateInputs

- src/granite_io/io/granite_3_2/output_processors/granite_3_2_output_parser.py
- tests/io/granite_3_2/output_processors/test_granite_3_2_output_parser.py
- tests/io/granite_3_2/output_processors/testdata/test_output_with_colons_citation_text.txt
This PR fixes parsing error for Granite 3.2 where citation text in model output contains a colon. For example:
```
<co>1</co> Document 2: "3f : foo bar"
```
It also adds some resilience around citation parsing to handle improperly formatted or inconsistent citations and continue as best as possible, avoiding exceptions where possible.
Fixes #117
> fix: Granite 3.2 parser error - colon in citation text

- .github/workflows/lint.yml
- .github/workflows/test_contrib.yml
- .github/workflows/test_e2e.yml
- .github/workflows/test_examples.yml
* CI is currently failing with out of disk when running examples. Trying to use free-disk-space consistently.
> ci: free disk space in more workflows before install python

- pyproject.toml
* Newer versions appear to have fixed bug (reason for our ceiling)
* Adding top end of range for these for semver compatibility
* Bump ruff for dependabot
> chore: bump litellm/openai past older release range

- src/granite_io/io/granite_3_2/output_processors/granite_3_2_output_parser.py
- src/granite_io/io/granite_3_3/output_processors/granite_3_3_output_parser.py
- tests/io/granite_3_2/input_processors/testdata/test_reasoning_prompt.txt
Updates include:
- Setting up defaults for logger
- Changing errors to warnings
- Changing infos to debug
- Fixing bad formatting on string outputs
Fixes #155
> Update logging for Granite output parsers

- tests/io/granite_3_2/input_processors/test_granite_3_2_input_processor.py
- tests/io/granite_3_3/input_processors/test_granite_3_3_input_processor.py
- tests/test_utils.py
One of the test cases will only work if the current month's name is exactly 3 letters long. This change fixes that.
> Fix broken test case

- notebooks/citations.ipynb
- pyproject.toml
- src/granite_io/visualization/__init__.py
- src/granite_io/visualization/citations.py
- src/granite_io/visualization/index.css
- src/granite_io/visualization/index.js
- tests/io/granite_3_2/input_processors/test_granite_3_2_input_processor.py
- tests/io/granite_3_2/output_processors/test_granite_3_2_output_parser.py
- tests/io/granite_3_2/output_processors/test_granite_3_2_output_processor.py
- tests/io/granite_3_3/input_processors/test_granite_3_3_input_processor.py
- tests/io/granite_3_3/output_processors/test_granite_3_3_output_parser.py
- tests/io/granite_3_3/output_processors/test_granite_3_3_output_processor.py
This PR adds a citations widget for visualizing citations. This includes the following changes:
- Add dependency for `anywidget` (the library on which the widget is based).
- Add code implementing the widget on top of the `anywidget` library.
- Add code that wraps the widget inside a python class that allows users of granite-io to create a widget by passing to it the input and output of the CitationsIOProcessor (i.e., a `ChatCompletionInputs` and a `ChatCompletionResults` object).
- Extends `citations` notebook by visualizing the generated citations using the widget.
> Add Citations Widget

- src/granite_io/backend/base.py
- src/granite_io/types.py
The `best_of` parameter is deprecated in vLLM and OpenAI (and probably some other platforms). See https://github.com/vllm-project/vllm/issues/13361 for the vLLM deprecation notice.
Recent builds of vLLM will refuse to run model inference if the `best_of` parameter is present and the 0.1 backend is enabled.
Existing code in our library sets the `best_of` parameter on all requests where the `n` parameter is not set to 1. In addition to crashing vLLM, this parameter modification can alter the semantics of generation requests that make use of other parameters like `top_k` and `top_p` to control which top generation results are produced.
This change set modifies the logic in `Backend` such that the base class no longer adds `best_of` parameter values to requests that did not contain them.
> Don't add best_of when not already present

- README.md
- pyproject.toml
- src/granite_io/io/citations/citations.py
- src/granite_io/io/granite_3_2/output_processors/granite_3_2_output_parser.py
- src/granite_io/io/granite_3_3/output_processors/granite_3_3_output_parser.py
- src/granite_io/io/hallucinations/hallucinations.py
- src/granite_io/io/retrieval/retrieval.py
- src/granite_io/optional.py
This PR makes the dependency on `nltk` optional. If `nltk` is not present and the user attempts to use a capability of the library that requires it, then an exception will be raised with an error message containing installation instructions for `nltk`. I've added `nltk` to the packages in the `[dev]` package set for developers.
> Make nltk dependency optional

- src/granite_io/io/granite_3_3/granite_3_3.py
- src/granite_io/io/granite_3_3/output_processors/granite_3_3_output_parser.py
- src/granite_io/io/granite_3_3/output_processors/granite_3_3_output_processor.py
- tests/io/granite_3_3/output_processors/test_granite_3_3_output_parser.py
- tests/io/granite_3_3/test_granite_3_3.py
Fix for issue #173. (Also fixes issue #156.)
Added a check and function to clean the old controls format. The new check `inputs.controls is None` enables the cleaning when no explicit controls have been specified.
Notebook to demonstrate fix: [granite-3_3-issue173-fix.ipynb.zip](https://github.com/user-attachments/files/20354973/granite-3_3-issue173-fix.ipynb.zip)
CSV comparing the three outputs: [granite-3_3-issue173-fix.csv](https://github.com/user-attachments/files/20355067/granite-3_3-issue173-fix.csv)
- `without_fix_no_controls` - old controls format appears in some response outputs
- `with_fix_no_controls` - with fix, no controls can be seen in the response output
- `with_fix_with_controls` - enabling the controls, correctly outputs the new controls format
> Fix for issue #173 - old controls format sometimes appear in granite 3.3 output

- notebooks/hallucinations.ipynb
- src/granite_io/io/rag_agent_lib/__init__.py
Update to the changes in #197: Remove output that was accidentally left in the Hallucination notebook. Also pulling in some preliminary changes to `src/granite_io/io/rag_agent_lib/__init__.py` to avoid merge conflicts later.
> Remove output from notebook

- src/granite_io/io/consts.py
- src/granite_io/io/granite_3_2/input_processors/granite_3_2_input_processor.py
- src/granite_io/io/granite_3_3/input_processors/granite_3_3_input_processor.py
- tests/io/granite_3_2/input_processors/test_granite_3_2_input_processor.py
- tests/io/granite_3_2/input_processors/testdata/test_remove_special_tokens_expected_prompt.txt
- tests/io/granite_3_2/input_processors/testdata/test_remove_special_tokens_input_json.txt
- tests/io/granite_3_3/input_processors/test_granite_3_3_input_processor.py
- tests/io/granite_3_3/input_processors/testdata/test_remove_special_tokens_expected_prompt.txt
- tests/io/granite_3_3/input_processors/testdata/test_remove_special_tokens_input_json.txt
PR closes #52. 
Optional removal of special tokens for Granite 3.2 and Granite 3.3 input processors. Same PR as the code is mostly the same for both versions.
1. Added param `sanitize` to the 3.2 and 3.3 inputs, values: `None` | `"inputs"` | `"aggressive"` (open to naming suggestions)
2. Special tokens are matched by regexes first, based on their intended usage, e.g. leaks from a tokenizer output or an injection attack
3. Remaining special tokens unmatched by regexes above are replaced with an empty string
4. Removal is done in the `model_validator` (after field validations) in the input processors
5. Added tests for 3.2 and 3.3 with an example to remove special tokens
I also removed a space on this line: https://github.com/ibm-granite/granite-io/blob/f77deaa7c5d6f3d908a4082dcb6ae9ad6a3ac3 …
> Add optional removal of special tokens from inputs

- src/granite_io/io/granite_3_3/output_processors/granite_3_3_output_parser.py
- src/granite_io/io/hallucinations/hallucinations.py
Fixes #246. Add init values for citation and hallucination objects in augment functions so that on errors, the objects have the required fields.
Includes commits from #242 as I'm dependent on both branches for dev for benchmarking composite intrinsics.
Update: Also contains fix for #248
> Fix for issue #246 incomplete augment of loop objects on error cases
